export const QUIZ_CONFIG = {
  MAX_QUESTION_COUNT: Number(process.env.NEXT_PUBLIC_MAX_QUESTION_COUNT) || 100,
  DEFAULT_QUESTION_COUNT: Number(process.env.NEXT_PUBLIC_DEFAULT_QUESTION_COUNT) || 10,
  DEFAULT_DIFFICULTY: process.env.NEXT_PUBLIC_DEFAULT_DIFFICULTY || "Medium",
  MAX_PROMPT_LENGTH: 45000 / 0.75,
  DIFFICULTY_LEVELS: ["Easy", "Medium", "Hard"] as const,
  DAILY_GENERATION_LIMIT: Number(process.env.DAILY_GENERATION_LIMIT) || 20,
} as const;

export type DifficultyLevel = typeof QUIZ_CONFIG.DIFFICULTY_LEVELS[number];